name: errors
description: A dart package that provides error classes
publish_to: 'none'

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  equatable: ^2.0.5


dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.24.9